/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChecklistItem { 'checked' : boolean, 'item' : string }
export type JobType = { 'repair' : null } |
  { 'inspection' : null } |
  { 'emergency' : null } |
  { 'maintenance' : null } |
  { 'installation' : null };
export interface PartUsed {
  'partNumber' : string,
  'partName' : string,
  'quantity' : bigint,
}
export type ReportStatus = { 'completed' : null } |
  { 'draft' : null } |
  { 'inProgress' : null };
export interface ServiceReport {
  'status' : ReportStatus,
  'clientName' : string,
  'assetId' : string,
  'jobType' : JobType,
  'date' : string,
  'faultDescription' : string,
  'partsUsed' : Array<PartUsed>,
  'engineerName' : string,
  'serialNumber' : string,
  'checklistItems' : Array<ChecklistItem>,
  'workPerformed' : string,
  'reportNumber' : bigint,
  'equipmentModel' : string,
  'location' : string,
  'remarks' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReport' : ActorMethod<[ServiceReport], bigint>,
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'getAllReports' : ActorMethod<[], Array<ServiceReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReportById' : ActorMethod<[bigint], [] | [ServiceReport]>,
  'getReportsByEngineer' : ActorMethod<[string], Array<ServiceReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateReport' : ActorMethod<[bigint, ServiceReport], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];