/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReportStatus = IDL.Variant({
  'completed' : IDL.Null,
  'draft' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const JobType = IDL.Variant({
  'repair' : IDL.Null,
  'inspection' : IDL.Null,
  'emergency' : IDL.Null,
  'maintenance' : IDL.Null,
  'installation' : IDL.Null,
});
export const PartUsed = IDL.Record({
  'partNumber' : IDL.Text,
  'partName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const ChecklistItem = IDL.Record({
  'checked' : IDL.Bool,
  'item' : IDL.Text,
});
export const ServiceReport = IDL.Record({
  'status' : ReportStatus,
  'clientName' : IDL.Text,
  'assetId' : IDL.Text,
  'jobType' : JobType,
  'date' : IDL.Text,
  'faultDescription' : IDL.Text,
  'partsUsed' : IDL.Vec(PartUsed),
  'engineerName' : IDL.Text,
  'serialNumber' : IDL.Text,
  'checklistItems' : IDL.Vec(ChecklistItem),
  'workPerformed' : IDL.Text,
  'reportNumber' : IDL.Nat,
  'equipmentModel' : IDL.Text,
  'location' : IDL.Text,
  'remarks' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func([ServiceReport], [IDL.Nat], []),
  'deleteReport' : IDL.Func([IDL.Nat], [], []),
  'getAllReports' : IDL.Func([], [IDL.Vec(ServiceReport)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReportById' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceReport)], ['query']),
  'getReportsByEngineer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceReport)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateReport' : IDL.Func([IDL.Nat, ServiceReport], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReportStatus = IDL.Variant({
    'completed' : IDL.Null,
    'draft' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'repair' : IDL.Null,
    'inspection' : IDL.Null,
    'emergency' : IDL.Null,
    'maintenance' : IDL.Null,
    'installation' : IDL.Null,
  });
  const PartUsed = IDL.Record({
    'partNumber' : IDL.Text,
    'partName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const ChecklistItem = IDL.Record({ 'checked' : IDL.Bool, 'item' : IDL.Text });
  const ServiceReport = IDL.Record({
    'status' : ReportStatus,
    'clientName' : IDL.Text,
    'assetId' : IDL.Text,
    'jobType' : JobType,
    'date' : IDL.Text,
    'faultDescription' : IDL.Text,
    'partsUsed' : IDL.Vec(PartUsed),
    'engineerName' : IDL.Text,
    'serialNumber' : IDL.Text,
    'checklistItems' : IDL.Vec(ChecklistItem),
    'workPerformed' : IDL.Text,
    'reportNumber' : IDL.Nat,
    'equipmentModel' : IDL.Text,
    'location' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func([ServiceReport], [IDL.Nat], []),
    'deleteReport' : IDL.Func([IDL.Nat], [], []),
    'getAllReports' : IDL.Func([], [IDL.Vec(ServiceReport)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReportById' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceReport)], ['query']),
    'getReportsByEngineer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateReport' : IDL.Func([IDL.Nat, ServiceReport], [], []),
  });
};

export const init = ({ IDL }) => { return []; };