/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceReport {
    status: ReportStatus;
    clientName: string;
    assetId: string;
    jobType: JobType;
    date: string;
    faultDescription: string;
    partsUsed: Array<PartUsed>;
    engineerName: string;
    serialNumber: string;
    checklistItems: Array<ChecklistItem>;
    workPerformed: string;
    reportNumber: bigint;
    equipmentModel: string;
    location: string;
    remarks: string;
}
export interface ChecklistItem {
    checked: boolean;
    item: string;
}
export interface PartUsed {
    partNumber: string;
    partName: string;
    quantity: bigint;
}
export interface UserProfile {
    name: string;
}
export enum JobType {
    repair = "repair",
    inspection = "inspection",
    emergency = "emergency",
    maintenance = "maintenance",
    installation = "installation"
}
export enum ReportStatus {
    completed = "completed",
    draft = "draft",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createReport(report: ServiceReport): Promise<bigint>;
    deleteReport(reportNumber: bigint): Promise<void>;
    getAllReports(): Promise<Array<ServiceReport>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getReportById(reportNumber: bigint): Promise<ServiceReport | null>;
    getReportsByEngineer(engineerName: string): Promise<Array<ServiceReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateReport(reportNumber: bigint, updatedReport: ServiceReport): Promise<void>;
}
import type { ChecklistItem as _ChecklistItem, JobType as _JobType, PartUsed as _PartUsed, ReportStatus as _ReportStatus, ServiceReport as _ServiceReport, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createReport(arg0: ServiceReport): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReport(to_candid_ServiceReport_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReport(to_candid_ServiceReport_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteReport(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async getAllReports(): Promise<Array<ServiceReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportById(arg0: bigint): Promise<ServiceReport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByEngineer(arg0: string): Promise<Array<ServiceReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByEngineer(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByEngineer(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateReport(arg0: bigint, arg1: ServiceReport): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReport(arg0, to_candid_ServiceReport_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReport(arg0, to_candid_ServiceReport_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_JobType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ReportStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportStatus): ReportStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceReport_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceReport): ServiceReport {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceReport]): ServiceReport | null {
    return value.length === 0 ? null : from_candid_ServiceReport_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReportStatus;
    clientName: string;
    assetId: string;
    jobType: _JobType;
    date: string;
    faultDescription: string;
    partsUsed: Array<_PartUsed>;
    engineerName: string;
    serialNumber: string;
    checklistItems: Array<_ChecklistItem>;
    workPerformed: string;
    reportNumber: bigint;
    equipmentModel: string;
    location: string;
    remarks: string;
}): {
    status: ReportStatus;
    clientName: string;
    assetId: string;
    jobType: JobType;
    date: string;
    faultDescription: string;
    partsUsed: Array<PartUsed>;
    engineerName: string;
    serialNumber: string;
    checklistItems: Array<ChecklistItem>;
    workPerformed: string;
    reportNumber: bigint;
    equipmentModel: string;
    location: string;
    remarks: string;
} {
    return {
        status: from_candid_ReportStatus_n12(_uploadFile, _downloadFile, value.status),
        clientName: value.clientName,
        assetId: value.assetId,
        jobType: from_candid_JobType_n14(_uploadFile, _downloadFile, value.jobType),
        date: value.date,
        faultDescription: value.faultDescription,
        partsUsed: value.partsUsed,
        engineerName: value.engineerName,
        serialNumber: value.serialNumber,
        checklistItems: value.checklistItems,
        workPerformed: value.workPerformed,
        reportNumber: value.reportNumber,
        equipmentModel: value.equipmentModel,
        location: value.location,
        remarks: value.remarks
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    draft: null;
} | {
    inProgress: null;
}): ReportStatus {
    return "completed" in value ? ReportStatus.completed : "draft" in value ? ReportStatus.draft : "inProgress" in value ? ReportStatus.inProgress : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repair: null;
} | {
    inspection: null;
} | {
    emergency: null;
} | {
    maintenance: null;
} | {
    installation: null;
}): JobType {
    return "repair" in value ? JobType.repair : "inspection" in value ? JobType.inspection : "emergency" in value ? JobType.emergency : "maintenance" in value ? JobType.maintenance : "installation" in value ? JobType.installation : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceReport>): Array<ServiceReport> {
    return value.map((x)=>from_candid_ServiceReport_n10(_uploadFile, _downloadFile, x));
}
function to_candid_JobType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ReportStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): _ReportStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceReport_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceReport): _ServiceReport {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ReportStatus;
    clientName: string;
    assetId: string;
    jobType: JobType;
    date: string;
    faultDescription: string;
    partsUsed: Array<PartUsed>;
    engineerName: string;
    serialNumber: string;
    checklistItems: Array<ChecklistItem>;
    workPerformed: string;
    reportNumber: bigint;
    equipmentModel: string;
    location: string;
    remarks: string;
}): {
    status: _ReportStatus;
    clientName: string;
    assetId: string;
    jobType: _JobType;
    date: string;
    faultDescription: string;
    partsUsed: Array<_PartUsed>;
    engineerName: string;
    serialNumber: string;
    checklistItems: Array<_ChecklistItem>;
    workPerformed: string;
    reportNumber: bigint;
    equipmentModel: string;
    location: string;
    remarks: string;
} {
    return {
        status: to_candid_ReportStatus_n5(_uploadFile, _downloadFile, value.status),
        clientName: value.clientName,
        assetId: value.assetId,
        jobType: to_candid_JobType_n7(_uploadFile, _downloadFile, value.jobType),
        date: value.date,
        faultDescription: value.faultDescription,
        partsUsed: value.partsUsed,
        engineerName: value.engineerName,
        serialNumber: value.serialNumber,
        checklistItems: value.checklistItems,
        workPerformed: value.workPerformed,
        reportNumber: value.reportNumber,
        equipmentModel: value.equipmentModel,
        location: value.location,
        remarks: value.remarks
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportStatus): {
    completed: null;
} | {
    draft: null;
} | {
    inProgress: null;
} {
    return value == ReportStatus.completed ? {
        completed: null
    } : value == ReportStatus.draft ? {
        draft: null
    } : value == ReportStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    repair: null;
} | {
    inspection: null;
} | {
    emergency: null;
} | {
    maintenance: null;
} | {
    installation: null;
} {
    return value == JobType.repair ? {
        repair: null
    } : value == JobType.inspection ? {
        inspection: null
    } : value == JobType.emergency ? {
        emergency: null
    } : value == JobType.maintenance ? {
        maintenance: null
    } : value == JobType.installation ? {
        installation: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
